version: "3.8"
services:
  frontend:
    build: .
    ports:
      - "3000:80"

  backend:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data

  sqlite:
    image: nouchka/sqlite3
    volumes:
      - ./data:/data
